services:
  postgres:
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=sitrep
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=Electable-Regalia-Hasty-Sedative
      - APP_USER_PASSWORD=Coping-Olympics-Importer-Datebook
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
