services:
  postgres:
    image: 'postgres:17'
    environment:
      - POSTGRES_DB=sitrep
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
