#== Application
spring.application.name=sitrep
spring.threads.virtual.enabled=true

#== Persistence
spring.datasource.name=sitrep
spring.datasource.username=dev
spring.datasource.password=secret-dev-password